### ISSUE TITLE
Linter's bug when dealing with cyrillic characters

### ISSUE THREAD

**Issue by ailjushkin** [SublimeLinter/SublimeLinter-json#12]
There is a bug, when I have an UTF-8 encoded document and there is normal utf-8 cyrillic characters.
So when you want to prettify that kind of json file, plugin reads document, prettifies that and outputs hashes instead of cyrillic letters.

So for example, try to prettify this text:

<pre>
{
   "billStatus": {
            "name": "Не оплачен"
        }   
}
</pre>

Plugin will output this like

<pre>
{
    "billStatus": {
        "name": "\u041d\u0435 \u043e\u043f\u043b\u0430\u0447\u0435\u043d"
    }
}
</pre>

This is a problem, because plugin should not change encoding of a file. It should determine it correctly. At least, it should determine when a file in UTF-8 encoding.

Thank you.

**Comment by skj3gg** [comment]
What linter are you using?




What is the output of running this linter from the command line? Is it also the hashes?

**Comment by PositiveAlex** [comment]
@skj3gg I'm using JsonLint plugin. How can I run this linter from the command line ?

**Comment by skj3gg** [comment]
Opps, didn't realize we were in the SublimeLinter-json repository, sorry! There is no command line linter.

Are you using strict or loose json?

**Comment by PositiveAlex** [comment]
I'm using strict json, yes.

18:45, Ср, 01.04.2015, Blake Grotewold <notifications@github.com>:

**Comment by braver** [comment]
Recent versions don't seem to have this problem
