### ISSUE TITLE
Support for JavaScript Next package

### ISSUE THREAD

**Issue by OliverJAsh** [SublimeLinter/SublimeLinter-json#13]
https://github.com/Benvie/JavaScriptNext.tmLanguage

This package includes syntax files for JSON.

Would it be possible to add support?

**Comment by peduxe** [comment]
Bit late to this but you can map it in SublimeLinter user settings.

This is how I done for javascript babel.

`syntax_map` on SublimeLinter user settings:
```json
"syntax_map": {
  "html (django)": "html",
  "html (rails)": "html",
  "html 5": "html",
  "javascript (babel)": "javascript",
  "json (babel)": "json",
  "php": "html",
  "python django": "python"
},

**Comment by LeonardoGentile** [comment]
@OliverJAsh try this in `User/SublimeLinter.sublime-settings`

```
"syntax_map": {
  "json (javascriptnext)": "json" // add this to the already existing key-values
}
```
