### ISSUE TITLE
No comma doesn't throw exeptions and throws exceptions where there is no errors 

### ISSUE THREAD

**Issue by wzup** [SublimeLinter/SublimeLinter-json#15]
Here are screenshots.
No errors, but marked as error:

![sublime text unregistered 2016-02-05 13 01 25](https://cloud.githubusercontent.com/assets/3880497/12838414/e917413e-cc08-11e5-9074-bb1e81e69814.png)

Obvious error, but no marks:

![sublime text unregistered 2016-02-05 13 02 47](https://cloud.githubusercontent.com/assets/3880497/12838418/fe21d062-cc08-11e5-9793-8c37223a882a.png)

**Comment by LeonardoGentile** [comment]
Related to #11

**Comment by braver** [comment]
I can't reproduce any of this in recent versions of the packages and ST3.
