### ISSUE TITLE
Detect duplicate keys

### ISSUE THREAD

**Issue by MartyGentillon** [SublimeLinter/SublimeLinter-json#19]
Duplicate keys are a common enough problem in large json files that it would be useful to have the linter inspect for them.

**Comment by braver** [comment]
This plugin uses the json parser from Sublime Text, and apparently it doesn't catch this error. Nothing we can do about it. You can probably use eslint if you want more features in your json linting.

**Comment by MartyGentillon** [comment]
At least in strict mode, you are using the standard python json parser.  It is quite capable of being extended to detect duplicate keys using the object_pairs_hook.  This should be possible when using that.  If I have to give up comments to detect duplicate keys, that might be a worthwhile trade.

**Comment by kaste** [comment]
This totally non trivial so a PR to prove the concept at least would be necessary. The problem here is not to write the object pairs hook, but the linter must return at least the line and maybe the col of the error. That's the non trivial part I think.
