### ISSUE TITLE
How to associate local JSON schemas with yaml files?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [SublimeLinter/SublimeLinter-json#22]
I want to write the equivalent to this [`.vscode/settings.json`](https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/blob/master/.vscode/settings.json) file:

```json
{
    "yaml.schemas": {
        "https://json.schemastore.org/hugo.json": "config.yml",
        "static/schemas/about/environment/configs.json": "data/about/environment/configs/*.yml",
        "static/schemas/about/environment/extensions.json": "data/about/environment/extensions/*.yml",
        "static/schemas/about/skills/editors.json": "data/about/skills/editors/*.yml",
        "static/schemas/about/skills/languages.json": "data/about/skills/languages/*.yml",
        "static/schemas/about/skills/vcs.json": "data/about/skills/vcs/*.yml",
        "static/schemas/about/achievements.json": "data/about/achievements.yml",
        "static/schemas/about/organizations.json": "data/about/organizations.yml",
        "static/schemas/about/presentations.json": "data/about/presentations.yml",
    }
}
```

How can I do that?

**Comment by kaste** [comment]
Just for the future reader:  How did you solve that?  I know this plugin is a dumb, but fast JSON linter basically just for syntax errors.  Did you use the (newer)  https://github.com/jacksmith15/SublimeLinter-contrib-jsonschema-lint?

**Comment by EmilySeville7cfg** [comment]
I've switched to [another plugin](https://github.com/sublimelsp/LSP-json) because I wanted to have completions in addition to JSON schema validation.
